<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.17763.0</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PlatformTarget>x64</PlatformTarget>
    <AssemblyName>Mim0.TelegramRPC</AssemblyName>
    <RootNamespace>Mim0.TelegramRPC</RootNamespace>
    <ApplicationIcon>assets\Mim0.ico</ApplicationIcon>
    <Company>Mim0</Company>
    <Product>Mim0 | TelegramRPC</Product>
    <Description>Lightweight Windows music to Discord Rich Presence.</Description>
    <Copyright>Copyright © 2026 Mim0</Copyright>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="ModernSettingsWindow.cs" />
    <PackageReference Include="Dubya.WindowsMediaController" Version="2.5.6" />
    <PackageReference Include="DiscordRichPresence" Version="1.6.1.70" />
  </ItemGroup>
</Project>
